# Lidhja me DB
spring.datasource.url=jdbc:mysql://localhost:3306/my1application
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Lejon Hibernate te krijoje/perditesoje tabelat
spring.jpa.hibernate.ddl-auto=update
spring.main.banner-mode=off

# Shfaq SQL ne console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true